### ISSUE TITLE
是否这个sdk不支持python3.7.4  

### ISSUE THREAD

**Issue by ttcool** [huaweicloud/huaweicloud-sdk-python-obs#7]
huaweicloud-sdk-python-obs  版本  Version 3.20.11     python 版本 3.7.4   上传文件返回状态码  403 ，python版本3.7.0 ，3.52 正常返回状态200，是否这个sdk不支持python3.7.4

**Comment by ttcool** [comment]
from obs import ObsClient
from obs import LogConf


obsClient = ObsClient(
    access_key_id=obs_access_key_id,
    secret_access_key=obs_secret_access_key,
    server=obs_server
)
obsClient.initLog(LogConf('./log.conf'), 'obs_logger');

def upload_obs_file(bucket_name,filename,uploadFile):
    taskNum = 5
    partSize = 10 * 1024 * 1024
    enableCheckpoint = True
    try:
        resp = obsClient.uploadFile(bucket_name, filename, uploadFile, partSize, taskNum, enableCheckpoint)
        print(resp)
        if resp.status < 300:
            print('requestId:', resp.requestId)
        else:
            print('errorCode:', resp.errorCode)
            print('errorMessage:', resp.errorMessage)
    except:
        import traceback
        print(traceback.format_exc())

upload_obs_file('front','test20201202.txt','/data/test20201202.txt')


Traceback (most recent call last):
  File "obs_test.py", line 22, in upload_obs_file
    resp = obsClient.uploadFile(bucket_name, filename, uploadFile, partSize, taskNum, enableCheckpoint)
  File "/usr/local/python/lib/python3.7/site-packages/esdk_obs_python-3.20.11-py3.7.egg/obs/client.py", line 166, in wrapper
    raise e
  File "/usr/local/python/lib/python3.7/site-packages/esdk_obs_python-3.20.11-py3.7.egg/obs/client.py", line 162, in wrapper
    ret = func(*args, **kwargs)
  File "/usr/local/python/lib/python3.7/site-packages/esdk_obs_python-3.20.11-py3.7.egg/obs/client.py", line 2207, in uploadFile
    checkSum, metadata, progressCallback, self, headers, extensionHeaders=extensionHeaders)
  File "/usr/local/python/lib/python3.7/site-packages/esdk_obs_python-3.20.11-py3.7.egg/obs/transfer.py", line 44, in _resumer_upload
    headers, extensionHeaders=extensionHeaders)
  File "/usr/local/python/lib/python3.7/site-packages/esdk_obs_python-3.20.11-py3.7.egg/obs/transfer.py", line 140, in __init__
    raise Exception('head bucket {0} failed. Please check. Status:{1}.'.format(self.bucketName, resp.status))
Exception: head bucket front failed. Please check. Status:403.

**Comment by ttcool** [comment]
error message

**Comment by x00403408** [comment]
建议您提供一些更详细的错误信息，可以测试get接口以获取对应403情况下的errorCode以及errorMessage信息；另外可以提供一下SDK的日志以协助更好地定位返回403错误的具体原因；

**Comment by huaweiclouddev** [comment]
## 🤖 Stale Bot

⏰ 已 2060 天无活动，标记为过期。如有更新将自动取消。30 天后无活动将自动关闭。

<sub>集中管理 · 详见 [治理规范](https://github.com/huaweicloud/.github/blob/main/GOVERNANCE.md)</sub>

**Comment by huaweiclouddev** [comment]
## 🤖 Stale Bot

🔒 因 35 天无活动自动关闭。如需重新打开请评论。

<sub>集中管理 · 详见 [治理规范](https://github.com/huaweicloud/.github/blob/main/GOVERNANCE.md)</sub>
